FROM node:16-alpine AS builder

WORKDIR /app

COPY . .

# RUN npm install
RUN npm ci

RUN npm run generate


FROM nginx:stable-alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html/
COPY ./monstermatches.conf /etc/nginx/conf.d/

CMD ["nginx", "-g", "daemon off;"]

EXPOSE 80 3000
